#pragma once

enum VboEnum {
	VERTICES,
	INDICES,
	NORMALS,
	TEX_COORDS,
	TANGENTS,
	BINORMALS,
	NUM_VBOS
};

// Locations of attributes in shaders
enum LocationEnum {
	VERTICES_LOCATION = 0,
	NORMALS_LOCATION = 1,
	TEXTURE_COORDINATES_LOCATION = 2,
	MODEL_MATRIX_LOCATION = 3,
	VIEW_MATRIX_LOCATION = 4,
	NORMAL_MATRIX_LOCATION = 5,
	PROJECTION_MATRIX_LOCATION = 6,
	TANGENTS_LOCATION = 7,
	BINORMALS_LOCATION = 8,
	DIFFUSE_SAMPLER_LOCATION = 9,
	SPECULAR_SAMPLER_LOCATION = 10,
	NORMAL_SAMPLER_LOCATION = 11,
	DISPLACEMENT_SAMPLER_LOCATION = 12,
	MATERIAL_AMBIENT_LOCATION = 13,
	MATERIAL_DIFFUSE_LOCATION = 14,
	MATERIAL_SPECULAR_LOCATION = 15,
	MATERIAL_SHININESS_LOCATION = 16,
	LIGHT_POSITION_LOCATION = 17,
	LIGHT_AMBIENT_LOCATION = 18,
	LIGHT_DIFFUSE_LOCATION = 19,
	LIGHT_SPECULAR_LOCATION = 20,
	PARALLAX_STRENGTH_LOCATION = 21
};